import { expect, test } from "@playwright/test";

test("checkbox groups own selection, native submission, disabled states, and canceled reset", async ({ page }) => {
  await page.goto("/checkbox-group");
  const group = page.getByRole("group", { name: "Channels", exact: true });
  const email = group.getByRole("checkbox", { name: "Email", exact: true });
  const desktop = group.getByRole("checkbox", { name: "Desktop", exact: true });
  await expect(email).toBeChecked();
  await email.focus();
  await page.keyboard.press("Space");
  await expect(email).not.toBeChecked();
  await page.keyboard.press("Tab");
  await expect(desktop).toBeFocused();
  await page.keyboard.press("Space");
  await expect(desktop).toBeChecked();
  await expect(group.getByRole("checkbox", { name: "SMS" })).toBeDisabled();
  const controlled = page.getByRole("group", { name: "Controlled channels", exact: true }).getByRole("checkbox", { name: "Email", exact: true });
  await controlled.focus();
  await page.keyboard.press("Space");
  await expect(controlled).toBeChecked();
  const rejected = page.getByRole("group", { name: "Rejected channels", exact: true }).getByRole("checkbox", { name: "Email", exact: true });
  await rejected.focus();
  await page.keyboard.press("Space");
  await expect(rejected).not.toBeChecked();
  const readonly = page.getByRole("group", { name: "Readonly channels", exact: true }).getByRole("checkbox", { name: "Email", exact: true });
  await readonly.focus();
  await page.keyboard.press("Space");
  await expect(readonly).toBeChecked();
  await page.getByRole("button", { name: "Inspect form" }).click();
  await expect(page.getByLabel("Form values")).toHaveText('[["channels","desktop"],["controlled","email"],["readonly","email"],["external","desktop"],["external-switch","on"]]');
  const external = page.getByRole("group", { name: "External channels", exact: true }).getByRole("checkbox", { name: "Desktop", exact: true });
  await external.focus();
  await page.keyboard.press("Space");
  const externalSwitch = page.getByRole("switch", { name: "External switch" });
  await externalSwitch.focus();
  await page.keyboard.press("Space");
  await page.getByRole("button", { name: "Reset channels" }).click();
  await expect(email).toBeChecked();
  await expect(desktop).not.toBeChecked();
  await expect(controlled).toBeChecked();
  await expect(external).toBeChecked();
  await expect(externalSwitch).toBeChecked();
  await email.focus();
  await page.keyboard.press("Space");
  await page.getByRole("button", { name: "Cancel reset: false" }).click();
  await page.getByRole("button", { name: "Reset channels" }).click();
  await expect(email).not.toBeChecked();
  await page.getByRole("button", { name: "Toggle disabled" }).click();
  for (const input of await group.getByRole("checkbox").all()) await expect(input).toBeDisabled();
});

test("removing a focused option moves to the nearest enabled choice without stealing deliberate focus", async ({ page }) => {
  await page.goto("/checkbox-group");
  const group = page.getByRole("group", { name: "Channels", exact: true });
  await group.getByRole("checkbox", { name: "Email", exact: true }).focus();
  const refresh = page.getByRole("button", { name: "Refresh options" });
  await refresh.click();
  await expect(refresh).toBeFocused();
  await refresh.click();
  await group.getByRole("checkbox", { name: "Email", exact: true }).focus();
  await page.getByRole("button", { name: "Remove email" }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
  await expect(group.getByRole("checkbox", { name: "Desktop", exact: true })).toBeFocused();
  await page.getByRole("button", { name: "Clear options" }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
  await expect(group.getByRole("checkbox")).toHaveCount(0);
  await expect(group).toBeFocused();
  await expect(group).toHaveCSS("outline-style", "solid");
});

test("group hydration and refreshed option objects preserve edits, labels, and focused identities", async ({ page }) => {
  let release: () => void = () => {};
  const barrier = new Promise<void>(resolve => { release = resolve; });
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.route("**/*", async route => { if (route.request().resourceType() === "script") await barrier; await route.continue(); });
  try {
    await page.goto("/checkbox-group", { waitUntil: "commit" });
    const group = page.getByRole("group", { name: "Channels", exact: true });
    const email = group.getByRole("checkbox", { name: "Email", exact: true });
    const desktop = group.getByRole("checkbox", { name: "Desktop", exact: true });
    await email.focus();
    await page.keyboard.press("Space");
    await desktop.focus();
    await page.keyboard.press("Space");
    await desktop.evaluate(element => element.setAttribute("data-server-control", "retained"));
    release();
    await expect(page.locator('[data-sheen-portal="root"]')).toHaveAttribute("data-sheen-ready", "true");
    await expect(email).not.toBeChecked();
    await expect(desktop).toBeChecked();
    await expect(desktop).toBeFocused();
    await expect(desktop).toHaveAttribute("data-server-control", "retained");
    await page.getByRole("button", { name: "Refresh options" }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
    await expect(desktop).toBeFocused();
    await expect(desktop).toBeChecked();
    await expect(desktop).toHaveAttribute("data-server-control", "retained");
    await expect(group.locator("label")).toHaveText(["SMS", "Desktop", "Email"]);
    await email.focus();
    await email.evaluate(element => element.setAttribute("data-reordered-control", "retained"));
    await page.getByRole("button", { name: "Refresh options" }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
    await expect(email).toBeFocused();
    await expect(email).toHaveAttribute("data-reordered-control", "retained");
    await expect(email).not.toBeChecked();
    await desktop.focus();
    await page.getByRole("button", { name: "Toggle validation" }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
    await expect(desktop).toBeFocused();
    await expect(group).toHaveAttribute("aria-invalid", "true");
    await expect(group).toHaveAccessibleDescription("Choose delivery channels Choose another channel");
    await page.getByRole("button", { name: "Toggle direction" }).click();
    await expect(group).toHaveCSS("direction", "rtl");
    await expect(desktop).toHaveAttribute("data-server-control", "retained");
    expect(errors).toEqual([]);
  } finally { release(); }
});
