import { expect, test } from "@playwright/test";

test("checkbox keyboard activation, controlled ownership, mixed state, and native forms", async ({ page }) => {
  await page.goto("/checkbox");
  const alerts = page.getByRole("checkbox", { name: "Uncontrolled alerts", exact: true });
  await expect(alerts).toBeChecked();
  await alerts.focus();
  await page.keyboard.press("Space");
  await expect(alerts).not.toBeChecked();
  await page.keyboard.press("Tab");
  const controlled = page.getByRole("checkbox", { name: "Controlled alerts", exact: true });
  await expect(controlled).toBeFocused();
  await page.keyboard.press("Space");
  await expect(controlled).toBeChecked();
  await page.keyboard.press("Tab");
  await page.keyboard.press("Space");
  await expect(page.getByRole("checkbox", { name: "Rejected change" })).not.toBeChecked();
  const mixed = page.getByRole("checkbox", { name: "Partial selection" });
  await expect(mixed).toBeChecked({ indeterminate: true });
  await mixed.focus();
  await page.keyboard.press("Space");
  await expect(mixed).toBeChecked();
  await expect(mixed).not.toBeChecked({ indeterminate: true });
  await page.keyboard.press("Tab");
  const readonly = page.getByRole("checkbox", { name: "Read-only choice" });
  await expect(readonly).toBeFocused();
  await page.keyboard.press("Space");
  await expect(readonly).toBeChecked();
  await expect(page.getByRole("checkbox", { name: "Disabled choice" })).toBeDisabled();
  await page.getByRole("button", { name: "Inspect form" }).click();
  await expect(page.getByLabel("Form values")).toHaveText('[["controlled","on"],["readonly","on"]]');
  await page.getByRole("button", { name: "Reset choices" }).click();
  await expect(alerts).toBeChecked();
  await expect(controlled).toBeChecked();
  await alerts.focus();
  await page.keyboard.press("Space");
  await page.getByRole("button", { name: "Cancel reset: false" }).click();
  await page.getByRole("button", { name: "Reset choices" }).click();
  await expect(alerts).not.toBeChecked();
});

test("checkbox hydration retains native identity, associations, focus, and logical layout", async ({ page }) => {
  let release: () => void = () => {};
  const barrier = new Promise<void>(resolve => { release = resolve; });
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.route("**/*", async route => { if (route.request().resourceType() === "script") await barrier; await route.continue(); });
  try {
    await page.goto("/checkbox", { waitUntil: "commit" });
    const input = page.getByRole("checkbox", { name: "Uncontrolled alerts", exact: true });
    await expect(input).toBeChecked();
    await input.evaluate(element => element.setAttribute("data-server-control", "retained"));
    const indicator = input.locator("xpath=..").locator(".sheen-checkbox-indicator");
    await expect(indicator).toHaveCSS("visibility", "visible");
    await input.focus();
    await page.keyboard.press("Space");
    await expect(input).not.toBeChecked();
    await expect(indicator).toHaveCSS("visibility", "hidden");
    const controlled = page.getByRole("checkbox", { name: "Controlled alerts", exact: true });
    await controlled.focus();
    await page.keyboard.press("Space");
    const rejected = page.getByRole("checkbox", { name: "Rejected change" });
    await rejected.focus();
    await page.keyboard.press("Space");
    await expect(rejected).toBeChecked();
    await input.focus();
    release();
    await expect(page.locator('[data-sheen-portal="root"]')).toHaveAttribute("data-sheen-ready", "true");
    await expect(input).toHaveAttribute("data-server-control", "retained");
    await expect(input).not.toBeChecked();
    await expect(input).not.toHaveAttribute("data-checked", "");
    await expect(indicator).toHaveCSS("visibility", "hidden");
    await expect(controlled).toBeChecked();
    await expect(rejected).not.toBeChecked();
    await page.keyboard.press("Space");
    await expect(input).toBeChecked();
    await input.focus();
    await page.getByRole("button", { name: "Toggle validation" }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
    await expect(input).toBeFocused();
    await expect(input).toHaveAttribute("aria-invalid", "true");
    await expect(input).toHaveAccessibleDescription("Workspace notifications Review this choice");
    await page.getByRole("button", { name: "Toggle direction" }).click();
    const root = input.locator("xpath=../..");
    const label = await root.locator("label").boundingBox();
    const control = await root.locator(".sheen-checkbox-control").boundingBox();
    expect(label).not.toBeNull();
    expect(control).not.toBeNull();
    expect(label!.x).toBeLessThan(control!.x);
    await expect(input).toHaveAttribute("data-server-control", "retained");
    expect(errors).toEqual([]);
  } finally { release(); }
});
