import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import AxeBuilder from "@axe-core/playwright";

test("only accepted constraints summarize columns and preserve saved layout and restoration", async ({ page }) => {
  await page.goto("/constrained-columns");
  const summary = page.getByRole("group", { name: "Fields fixed by the accepted filter" });
  const status = page.getByRole("columnheader", { name: /Status/ });
  const preferences = page.getByLabel("Accepted column preferences");
  await expect(status).toBeVisible();
  await expect(summary).toHaveCount(0);
  const original = await preferences.textContent();
  const row = page.locator('tr[data-row-id="record-1"]');
  await row.evaluate(element => element.setAttribute("data-retained", "yes"));
  const request = page.waitForRequest(url => url.url().includes("/api/constrained-table"));
  await page.getByRole("button", { name: "Active only", exact: true }).click();
  await request;
  await expect(status).toBeVisible();
  await expect(summary).toHaveCount(0);
  await expect(summary).toContainText("Status: Active · 4 matching results");
  await expect(status).toHaveCount(0);
  await expect(row).toHaveAttribute("data-retained", "yes");
  await expect(preferences).toHaveText(original ?? "");
  expect((await new AxeBuilder({ page }).include("main").analyze()).violations).toEqual([]);
  await page.getByRole("button", { name: "Restore Status column", exact: true }).press("Enter");
  await expect(status).toBeVisible();
  await expect(status.getByRole("button").first()).toBeFocused();
  await expect(status).toHaveAttribute("data-pin", "end");
  await expect(summary).toHaveCount(0);
  await expect(preferences).toHaveText(original ?? "");
  await page.getByRole("button", { name: "Single result", exact: true }).click();
  await expect(page.getByText("Record 2", { exact: true })).toHaveCount(0);
  await expect(status).toBeVisible();
  await expect(summary).toHaveCount(0);
});

test("empty and single results use full matching counts and export retains summarized fields", async ({ page }) => {
  await page.goto("/constrained-columns");
  const summary = page.getByRole("group", { name: "Fields fixed by the accepted filter" });
  await page.getByRole("button", { name: "Empty result", exact: true }).click();
  await expect(summary).toContainText("Status: Active · 0 matching results");
  await page.getByRole("button", { name: "Single result", exact: true }).click();
  await expect(summary).toContainText("Status: Active · 1 matching results");
  await page.getByRole("button", { name: "Active only", exact: true }).click();
  await expect(summary).toContainText("Status: Active · 4 matching results");
  await page.getByRole("button", { name: "Export", exact: true }).click();
  const downloading = page.waitForEvent("download");
  await page.getByRole("menuitem", { name: "Export JSON", exact: true }).click();
  const download = await downloading;
  const path = await download.path();
  if (!path) throw new Error("Missing export artifact");
  const result: unknown = JSON.parse(await readFile(path, "utf8"));
  expect(result).toEqual([1, 2, 3, 6].map(sequence => ({ id: `record-${sequence}`, name: `Record ${sequence}`, status: "Active", sequence })));
});

test("pagination, failed refresh, and retry retain the accepted summary until replacement", async ({ page }) => {
  await page.goto("/constrained-columns");
  const summary = page.getByRole("group", { name: "Fields fixed by the accepted filter" });
  await page.getByRole("button", { name: "Active only", exact: true }).click();
  await expect(summary).toContainText("Status: Active · 4 matching results");
  await page.getByRole("button", { name: "Next page", exact: true }).click();
  await expect(page.getByText("Record 6", { exact: true })).toBeVisible();
  await expect(page.locator("tbody tr[data-row-id]")).toHaveCount(1);
  await expect(summary).toContainText("Status: Active · 4 matching results");
  const row = page.locator('tr[data-row-id="record-6"]');
  await row.evaluate(element => element.setAttribute("data-retained", "yes"));
  await page.getByRole("checkbox", { name: "Fail requests" }).press("Space");
  const failure = page.waitForResponse(response => response.url().includes("/api/constrained-table") && response.status() === 503);
  await page.getByRole("button", { name: "All statuses", exact: true }).click();
  await expect(summary).toContainText("Status: Active · 4 matching results");
  await expect(row).toHaveAttribute("data-retained", "yes");
  await failure;
  await expect(summary).toContainText("Status: Active · 4 matching results");
  await expect(row).toHaveAttribute("data-retained", "yes");
  await page.getByRole("checkbox", { name: "Fail requests" }).press("Space");
  const retry = page.waitForResponse(response => response.url().includes("/api/constrained-table") && response.ok());
  await page.getByRole("button", { name: "Retry", exact: true }).click();
  const response = await retry;
  expect(await response.json()).toMatchObject({ total: 6, facets: { status: { Active: 4, Paused: 1, Review: 1 } } });
  await expect(summary).toHaveCount(0);
  await expect(page.getByRole("columnheader", { name: /Status/ })).toBeVisible();
});
