import { expect, test } from "@playwright/test";

test("Dialog owns controlled requests, focuses explicit targets, and retains drafts on refresh", async ({ page }) => {
  await page.goto("/dialogs");
  const trigger = page.getByRole("button", { name: "Open settings", exact: true });
  await trigger.click();
  const dialog = page.getByRole("dialog", { name: "Settings", exact: true });
  const input = dialog.getByRole("textbox", { name: "Workspace name" });
  await expect(input).toBeFocused();
  await input.fill("Retained draft");
  await input.evaluate(element => element.setAttribute("data-original", "retained"));
  await dialog.getByRole("button", { name: "Refresh description" }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
  await expect(input).toBeFocused();
  await expect(input).toHaveValue("Retained draft");
  await expect(input).toHaveAttribute("data-original", "retained");
  await expect(dialog).toHaveAccessibleDescription("Updated without replacing the input.");
  await dialog.getByRole("button", { name: "Open nested settings" }).click();
  await expect(page.getByRole("dialog", { name: "Nested settings", exact: true })).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog", { name: "Nested settings", exact: true })).toHaveCount(0);
  await expect(dialog.getByRole("button", { name: "Open nested settings" })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(trigger).toBeFocused();
  const controlledTrigger = page.getByRole("button", { name: "Open controlled", exact: true });
  await controlledTrigger.click();
  const controlled = page.getByRole("dialog", { name: "Controlled settings", exact: true });
  await page.keyboard.press("Escape");
  await expect(controlled).toBeVisible();
  await expect(controlled.getByLabel("Close requests")).toHaveText("1");
  await controlled.getByRole("button", { name: "Owner closes" }).click();
  await expect(controlled).toHaveCount(0);
  await expect(controlledTrigger).toBeFocused();
});

test("Dialog locked dismissal and AlertDialog safe focus, outside handling, RTL geometry", async ({ page }) => {
  await page.goto("/dialogs");
  await page.getByRole("button", { name: "Open locked operation" }).click();
  const locked = page.getByRole("dialog", { name: "Locked operation" });
  await locked.getByRole("button", { name: "Locked: false" }).click();
  await expect(locked.getByRole("button", { name: "Close", exact: true })).toBeDisabled();
  await page.keyboard.press("Escape");
  await page.mouse.click(5, 5);
  await expect(locked).toBeVisible();
  await locked.getByRole("button", { name: "Locked: true" }).click();
  await page.keyboard.press("Escape");
  await expect(locked).toHaveCount(0);
  const trigger = page.getByRole("button", { name: "Review removal" });
  await trigger.click();
  const alert = page.getByRole("alertdialog", { name: "Remove workspace?" });
  await expect(alert).toHaveAccessibleDescription("Saved views will be removed.");
  await expect(alert.getByRole("button", { name: "Keep workspace" })).toBeFocused();
  await page.keyboard.press("Tab");
  await expect(alert.getByRole("button", { name: "Destructive action placeholder" })).toBeFocused();
  await page.keyboard.press("Shift+Tab");
  await expect(alert.getByRole("button", { name: "Keep workspace" })).toBeFocused();
  await page.mouse.click(5, 5);
  await expect(alert).toBeVisible();
  const geometry = await alert.evaluate(element => {
    const bounds = element.getBoundingClientRect();
    return { center: bounds.left + bounds.width / 2, expected: innerWidth / 2, direction: getComputedStyle(element).direction };
  });
  expect(geometry.direction).toBe("rtl");
  expect(Math.abs(geometry.center - geometry.expected)).toBeLessThan(1);
  await page.keyboard.press("Escape");
  await expect(alert).toHaveCount(0);
  await expect(trigger).toBeFocused();
});

test("Confirmation resolves decisions, rejects overlap, aborts, and settles on owner disposal", async ({ page }) => {
  await page.goto("/dialogs");
  const opener = page.getByRole("button", { name: "Ask confirmation" });
  const prompt = page.getByRole("alertdialog", { name: "Remove saved view?" });
  const result = page.getByLabel("Confirmation result");
  await opener.click();
  await expect(prompt.getByRole("button", { name: "Keep view" })).toBeFocused();
  await prompt.evaluate(element => { if (element instanceof HTMLElement) element.style.setProperty("--sheen-duration-normal", "1s"); });
  await prompt.getByRole("button", { name: "Remove view" }).click();
  await expect(result).toHaveText("true");
  await expect(prompt).toHaveCount(0);
  await expect(page.locator(".sheen-dialog[data-closed]")).toHaveCSS("animation-name", "sheen-dialog-exit");
  await expect(page.locator(".sheen-dialog[data-closed]")).toHaveAttribute("inert", "");
  await expect(opener).toBeFocused();
  await opener.click();
  await page.getByRole("button", { name: "Overlap confirmation", includeHidden: true }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
  await expect(result).toHaveText("createConfirm already has an unanswered request");
  await expect(prompt).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(result).toHaveText("false");
  await expect(opener).toBeFocused();
  await opener.click();
  await page.getByRole("button", { name: "Abort confirmation", includeHidden: true }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
  await expect(prompt).toHaveCount(0);
  await expect(result).toHaveText("false");
  await expect(opener).toBeFocused();
  await opener.click();
  await page.getByRole("button", { name: "Dispose confirmation owner", includeHidden: true }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
  await expect(prompt).toHaveCount(0);
  await expect(result).toHaveText("false");
  await expect(opener).toHaveCount(0);
});

test("Dialog transient motion honors reduced motion without animating the layout trigger", async ({ page }) => {
  await page.goto("/dialogs");
  const trigger = page.getByRole("button", { name: "Open settings", exact: true });
  await expect(trigger).toHaveCSS("animation-name", "none");
  await trigger.click();
  const dialog = page.getByRole("dialog", { name: "Settings", exact: true });
  await expect(dialog).toHaveCSS("animation-name", "sheen-dialog-enter");
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(trigger).toBeFocused();
  await page.emulateMedia({ reducedMotion: "reduce" });
  await trigger.click();
  await expect(dialog).toHaveCSS("animation-duration", "0s");
  await page.keyboard.press("Escape");
  await expect(trigger).toBeFocused();
});
