import { expect, test } from "@playwright/test";

test("radio groups navigate, enforce exclusivity, reject disabled/readonly changes, and serialize one value", async ({ page }) => {
  await page.goto("/radio-group");
  const group = page.getByRole("radiogroup", { name: "Cadence", exact: true });
  const live = group.getByRole("radio", { name: "Live", exact: true });
  const manual = group.getByRole("radio", { name: "Manual", exact: true });
  await live.focus();
  await page.keyboard.press("ArrowDown");
  await expect(manual).toBeFocused();
  await expect(manual).toBeChecked();
  await expect(live).not.toBeChecked();
  await group.locator(".sheen-radio-item[data-disabled] .sheen-radio-control").click();
  await expect(manual).toBeChecked();
  await manual.focus();
  await page.keyboard.press("ArrowDown");
  await expect(live).toBeFocused();
  await expect(live).toBeChecked();
  await page.keyboard.press("Tab");
  const controlled = page.getByRole("radiogroup", { name: "Controlled cadence", exact: true });
  await expect(controlled.getByRole("radio", { name: "Live", exact: true })).toBeFocused();
  await page.keyboard.press("ArrowDown");
  await expect(controlled.getByRole("radio", { name: "Manual", exact: true })).toBeChecked();
  const rejected = page.getByRole("radiogroup", { name: "Rejected cadence", exact: true });
  await rejected.getByRole("radio", { name: "Manual", exact: true }).focus();
  await page.keyboard.press("Space");
  await expect(rejected.getByRole("radio", { name: "Live", exact: true })).toBeChecked();
  await expect(rejected.getByRole("radio", { name: "Manual", exact: true })).not.toBeChecked();
  const readonly = page.getByRole("radiogroup", { name: "Readonly cadence", exact: true });
  await readonly.getByRole("radio", { name: "Manual", exact: true }).focus();
  await page.keyboard.press("Space");
  await expect(readonly.getByRole("radio", { name: "Live", exact: true })).toBeChecked();
  await expect(readonly.getByRole("radio", { name: "Manual", exact: true })).not.toBeChecked();
  const disabled = page.getByRole("radiogroup", { name: "Disabled cadence", exact: true });
  for (const radio of await disabled.getByRole("radio").all()) await expect(radio).toBeDisabled();
  await page.getByRole("button", { name: "Inspect values" }).click();
  await expect(page.getByLabel("Form values")).toHaveText('[["cadence","live"],["controlled","manual"],["rejected","live"],["readonly","live"],["external","manual"]]');
  await page.getByRole("button", { name: "Clear controlled selection" }).click();
  await expect(controlled.locator("input:checked")).toHaveCount(0);
  await page.getByRole("button", { name: "Validate required" }).click();
  await expect(page.getByLabel("Form values")).not.toHaveText("required accepted");
  const required = page.getByRole("radiogroup", { name: "Required cadence", exact: true });
  await required.getByRole("radio", { name: "Live", exact: true }).focus();
  await page.keyboard.press("Space");
  await page.getByRole("button", { name: "Validate required" }).click();
  await expect(page.getByLabel("Form values")).toHaveText("required accepted");
});

test("radio reset preserves controlled ownership and respects cancellation including external forms", async ({ page }) => {
  await page.goto("/radio-group");
  const group = page.getByRole("radiogroup", { name: "Cadence", exact: true });
  const controlled = page.getByRole("radiogroup", { name: "Controlled cadence", exact: true });
  const external = page.getByRole("radiogroup", { name: "External cadence", exact: true });
  for (const target of [group, controlled]) {
    await target.getByRole("radio", { name: "Manual", exact: true }).focus();
    await page.keyboard.press("Space");
  }
  await external.getByRole("radio", { name: "Live", exact: true }).focus();
  await page.keyboard.press("Space");
  await page.getByRole("button", { name: "Reset cadence" }).click();
  await expect(group.getByRole("radio", { name: "Live", exact: true })).toBeChecked();
  await expect(controlled.getByRole("radio", { name: "Manual", exact: true })).toBeChecked();
  await expect(external.getByRole("radio", { name: "Manual", exact: true })).toBeChecked();
  await group.getByRole("radio", { name: "Manual", exact: true }).focus();
  await page.keyboard.press("Space");
  await page.getByRole("button", { name: "Cancel reset: false" }).click();
  await page.getByRole("button", { name: "Reset cadence" }).click();
  await expect(group.getByRole("radio", { name: "Manual", exact: true })).toBeChecked();
});

test("horizontal radio navigation follows RTL geometry and empty groups have one entry stop", async ({ page }) => {
  await page.goto("/radio-group");
  const external = page.getByRole("radiogroup", { name: "External cadence", exact: true });
  await expect(external).toHaveAttribute("aria-orientation", "horizontal");
  const live = external.getByRole("radio", { name: "Live", exact: true });
  const manual = external.getByRole("radio", { name: "Manual", exact: true });
  await manual.focus();
  await page.keyboard.press("ArrowRight");
  await expect(live).toBeFocused();
  await expect(live).toBeChecked();
  await page.getByRole("button", { name: "Toggle direction" }).click();
  await live.focus();
  await page.keyboard.press("ArrowRight");
  await expect(manual).toBeFocused();
  await expect(manual).toBeChecked();
  const empty = page.getByRole("radiogroup", { name: "Controlled cadence", exact: true });
  await expect(empty.locator("input[tabindex='0']")).toHaveCount(1);
  await expect(empty.locator("input[tabindex='0']")).toHaveAttribute("value", "live");
});

test("radio hydration adopts native choices and retains focused options through refresh and removal", async ({ page }) => {
  let release: () => void = () => {};
  const barrier = new Promise<void>(resolve => { release = resolve; });
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.route("**/*", async route => { if (route.request().resourceType() === "script") await barrier; await route.continue(); });
  try {
    await page.goto("/radio-group", { waitUntil: "commit" });
    const group = page.getByRole("radiogroup", { name: "Cadence", exact: true });
    const live = group.getByRole("radio", { name: "Live", exact: true });
    const manual = group.getByRole("radio", { name: "Manual", exact: true });
    await expect(group).toHaveAccessibleDescription("Choose update frequency");
    await expect(live).toHaveAccessibleDescription("Continuous updates Choose update frequency");
    await manual.focus();
    await page.keyboard.press("Space");
    await expect(live).not.toBeChecked();
    await expect(manual).toBeChecked();
    await expect(manual.locator("xpath=..").locator(".sheen-radio-indicator")).toHaveCSS("visibility", "visible");
    await manual.evaluate(element => element.setAttribute("data-server-control", "retained"));
    const controlled = page.getByRole("radiogroup", { name: "Controlled cadence", exact: true });
    await controlled.getByRole("radio", { name: "Manual", exact: true }).focus();
    await page.keyboard.press("Space");
    const rejected = page.getByRole("radiogroup", { name: "Rejected cadence", exact: true });
    await rejected.getByRole("radio", { name: "Manual", exact: true }).focus();
    await page.keyboard.press("Space");
    await manual.focus();
    release();
    await expect(page.locator('[data-sheen-portal="root"]')).toHaveAttribute("data-sheen-ready", "true");
    await expect(manual).toBeFocused();
    await expect(manual).toBeChecked();
    await expect(manual).toHaveAttribute("data-checked", "");
    await expect(manual).toHaveAttribute("data-server-control", "retained");
    await expect(controlled.getByRole("radio", { name: "Manual", exact: true })).toBeChecked();
    await expect(rejected.getByRole("radio", { name: "Live", exact: true })).toBeChecked();
    await page.getByRole("button", { name: "Refresh options" }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
    await expect(manual).toBeFocused();
    await expect(manual).toHaveAttribute("data-server-control", "retained");
    await page.getByRole("button", { name: "Toggle error" }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
    await expect(manual).toBeFocused();
    await expect(group).toHaveAccessibleDescription("Choose update frequency Choose another cadence");
    await page.getByRole("button", { name: "Toggle direction" }).click();
    await expect(group).toHaveCSS("direction", "rtl");
    await live.focus();
    await page.getByRole("button", { name: "Remove live" }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
    await expect(manual).toBeFocused();
    await page.getByRole("button", { name: "Clear options" }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
    await expect(group).toBeFocused();
    await expect(group).toHaveCSS("outline-style", "solid");
    expect(errors).toEqual([]);
  } finally { release(); }
});
