import { expect, test } from "@playwright/test";

test("controlled drawer rejects every dismissal path until the app accepts closure", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.setViewportSize({ width: 600, height: 800 });
  await page.goto("/shell-drawer-controlled");
  const toggle = page.getByRole("button", { name: "Toggle sidebar", exact: true });
  await toggle.click();
  const drawer = page.getByRole("dialog", { name: "Sidebar", exact: true });
  const proposals = page.locator('output[aria-label="Drawer proposals"]');
  await expect(proposals).toHaveText("1");
  const draft = drawer.getByRole("textbox", { name: "Controlled drawer draft", exact: true });
  await draft.fill("Rejected dismissal retains this draft");
  await draft.evaluate(element => element.setAttribute("data-retained", "true"));
  await page.keyboard.press("Escape");
  await expect(proposals).toHaveText("2");
  await expect(draft).toBeFocused();
  const close = drawer.getByRole("button", { name: "Close", exact: true });
  await close.click();
  await expect(proposals).toHaveText("3");
  await expect(close).toBeFocused();
  await page.mouse.click(580, 500);
  await expect(proposals).toHaveText("4");
  await expect(drawer).toBeVisible();
  await close.focus();
  await page.keyboard.press("Tab");
  await expect(draft).toBeFocused();
  await expect(draft).toHaveAttribute("data-retained", "true");
  await expect(draft).toHaveValue("Rejected dismissal retains this draft");
  await drawer.getByRole("switch", { name: "Accept drawer closure", exact: true }).focus();
  await page.keyboard.press("Space");
  await close.click();
  await expect(proposals).toHaveText("5");
  await expect(toggle).toBeFocused();
  await expect(drawer).toHaveCount(0);
  await expect(toggle).toHaveAttribute("aria-expanded", "false");
  await page.setViewportSize({ width: 1100, height: 800 });
  await expect(toggle).toHaveAttribute("aria-expanded", "true");
  await expect(page.getByRole("textbox", { name: "Controlled drawer draft", exact: true })).toHaveValue("Rejected dismissal retains this draft");
  await page.setViewportSize({ width: 600, height: 800 });
  await expect(toggle).toHaveAttribute("aria-expanded", "false");
  await expect(proposals).toHaveText("5");
  expect(errors).toEqual([]);
});

test("controlled open preference survives desktop presentation without a synthetic close proposal", async ({ page }) => {
  await page.setViewportSize({ width: 600, height: 800 });
  await page.goto("/shell-drawer-controlled");
  await page.getByRole("button", { name: "Toggle sidebar", exact: true }).click();
  const drawer = page.getByRole("dialog", { name: "Sidebar", exact: true });
  const draft = page.getByRole("textbox", { name: "Controlled drawer draft", exact: true });
  await draft.fill("Controlled preference survives resize");
  await draft.evaluate(element => element.setAttribute("data-retained", "true"));
  await page.setViewportSize({ width: 1100, height: 800 });
  await expect(drawer).toHaveCount(0);
  await expect(draft).toHaveValue("Controlled preference survives resize");
  await expect(page.locator('output[aria-label="Drawer proposals"]')).toHaveText("1");
  await page.setViewportSize({ width: 600, height: 800 });
  await expect(drawer).toBeVisible();
  await expect(draft).toBeFocused();
  await expect(draft).toHaveValue("Controlled preference survives resize");
  await expect(draft).toHaveAttribute("data-retained", "true");
  await expect(page.locator('output[aria-label="Drawer proposals"]')).toHaveText("1");
});
