import { expect, test } from "@playwright/test";

test("retained sidebar owner survives desktop, modal close/reopen, and desktop return", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/sidebar-handoff");
  const draft = page.getByRole("textbox", { name: "Sidebar draft", exact: true });
  await draft.fill("Keep this local draft");
  await draft.evaluate(element => element.setAttribute("data-retained", "true"));
  await page.setViewportSize({ width: 600, height: 800 });
  await expect(page.getByRole("status", { name: "Layout mode", exact: true })).toHaveText("phone");
  await expect(draft).toHaveCount(0);
  const trigger = page.getByRole("button", { name: "Open sidebar", exact: true });
  await trigger.click();
  const dialog = page.getByRole("dialog", { name: "Sidebar", exact: true });
  await expect(dialog).toBeVisible();
  await expect(draft).toHaveAttribute("data-retained", "true");
  await expect(draft).toHaveValue("Keep this local draft");
  await page.getByRole("button", { name: "Sidebar choice Alpha", exact: true }).click();
  await expect(page.getByRole("listbox", { name: "Sidebar choice", exact: true })).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(dialog).toBeVisible();
  await expect(page.getByRole("listbox")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Sidebar choice Alpha", exact: true })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(trigger).toBeFocused();
  await trigger.click();
  await expect(draft).toBeFocused();
  await expect(draft).toHaveValue("Keep this local draft");
  await expect(draft).toHaveAttribute("data-retained", "true");
  await page.getByRole("button", { name: "Close", exact: true }).focus();
  await page.keyboard.press("Tab");
  await expect(draft).toBeFocused();
  await page.setViewportSize({ width: 1100, height: 800 });
  await expect(page.getByRole("status", { name: "Layout mode", exact: true })).toHaveText("desktop");
  await expect(dialog).toHaveCount(0);
  await expect(draft).toHaveAttribute("data-retained", "true");
  await expect(draft).toHaveValue("Keep this local draft");
  await page.getByRole("textbox", { name: "Main draft", exact: true }).fill("Background usable again");
  expect(errors).toEqual([]);
});
