import { expect, test } from "@playwright/test";

test("switch keyboard behavior, controlled rejection, and native form reset retain ownership", async ({ page }) => {
  await page.goto("/switch");
  const live = page.getByRole("switch", { name: "Live updates", exact: true });
  const controlled = page.getByRole("switch", { name: "Controlled setting", exact: true });
  const rejected = page.getByRole("switch", { name: "Rejected setting", exact: true });
  await live.focus();
  await expect(live).toBeChecked();
  await page.keyboard.press("Space");
  await expect(live).not.toBeChecked();
  await page.keyboard.press("Tab");
  await expect(controlled).toBeFocused();
  await page.keyboard.press("Space");
  await expect(controlled).toBeChecked();
  await page.keyboard.press("Tab");
  await expect(rejected).toBeFocused();
  await page.keyboard.press("Space");
  await expect(rejected).not.toBeChecked();
  await page.keyboard.press("Tab");
  const readonly = page.getByRole("switch", { name: "Readonly setting", exact: true });
  await expect(readonly).toBeFocused();
  await page.keyboard.press("Space");
  await expect(readonly).toBeChecked();
  await expect(page.getByRole("switch", { name: "Disabled setting", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Inspect values" }).click();
  await expect(page.getByLabel("Form values")).toHaveText('[["controlled","on"],["readonly","on"]]');
  await page.getByRole("button", { name: "Reset switches" }).click();
  await expect(live).toBeChecked();
  await expect(controlled).toBeChecked();
  await live.focus();
  await page.keyboard.press("Space");
  await page.getByRole("button", { name: "Cancel reset: false" }).click();
  await page.getByRole("button", { name: "Reset switches" }).click();
  await expect(live).not.toBeChecked();
});

test("switch pre-hydration changes update the thumb and hydrate without losing focus or state", async ({ page }) => {
  let release: () => void = () => {};
  const barrier = new Promise<void>(resolve => { release = resolve; });
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.route("**/*", async route => { if (route.request().resourceType() === "script") await barrier; await route.continue(); });
  try {
    await page.goto("/switch", { waitUntil: "commit" });
    const live = page.getByRole("switch", { name: "Live updates", exact: true });
    const track = live.locator("xpath=..").locator(".sheen-switch-control");
    await expect(live).toBeChecked();
    await expect(track).toHaveCSS("justify-content", "end");
    await live.evaluate(element => element.setAttribute("data-server-control", "retained"));
    await live.focus();
    await page.keyboard.press("Space");
    await expect(live).not.toBeChecked();
    await expect(track).not.toHaveCSS("justify-content", "end");
    const controlled = page.getByRole("switch", { name: "Controlled setting", exact: true });
    await controlled.focus();
    await page.keyboard.press("Space");
    const rejected = page.getByRole("switch", { name: "Rejected setting", exact: true });
    await rejected.focus();
    await page.keyboard.press("Space");
    await live.focus();
    release();
    await expect(page.locator('[data-sheen-portal="root"]')).toHaveAttribute("data-sheen-ready", "true");
    await expect(live).toHaveAttribute("data-server-control", "retained");
    await expect(live).toBeFocused();
    await expect(live).not.toBeChecked();
    await expect(live).not.toHaveAttribute("data-checked", "");
    await expect(controlled).toBeChecked();
    await expect(rejected).not.toBeChecked();
    await page.keyboard.press("Space");
    await expect(live).toBeChecked();
    await page.getByRole("button", { name: "Toggle error" }).evaluate(element => { if (element instanceof HTMLButtonElement) element.click(); });
    await expect(live).toBeFocused();
    await expect(live).toHaveAttribute("aria-invalid", "true");
    await expect(live).toHaveAccessibleDescription("Automatic refresh Connection unavailable");
    const thumb = track.locator(".sheen-switch-thumb");
    const ltrTrack = await track.boundingBox(), ltrThumb = await thumb.boundingBox();
    expect(ltrThumb!.x).toBeGreaterThan(ltrTrack!.x + ltrTrack!.width / 3);
    await page.getByRole("button", { name: "Toggle direction" }).click();
    const rtlTrack = await track.boundingBox(), rtlThumb = await thumb.boundingBox();
    expect(rtlThumb!.x).toBeLessThan(rtlTrack!.x + rtlTrack!.width / 3);
    await expect(live).toHaveAttribute("data-server-control", "retained");
    expect(errors).toEqual([]);
  } finally { release(); }
});
