packages:
  - packages/*
  - apps/*

minimumReleaseAge: 1440

patchedDependencies:
  solid-js@1.9.15: patches/solid-js@1.9.15.patch
  '@kobalte/utils@0.9.2': patches/@kobalte__utils@0.9.2.patch
  '@kobalte/core@0.13.13': patches/@kobalte__core@0.13.13.patch
