import assert from "node:assert/strict";
import { assessServerPage, compileFilter, countClientFacets, createClientView, createDebouncedSearch, createTableRequests, deserializeFilter, filterClientRows, paginateClientRows, parseFilter, parseSorting, resolvePagination, searchClientRows, serializeFilter, sortClientRows } from "@gemologic/sheen-table/core";
import type { FilterColumn, TablePagination } from "@gemologic/sheen-table/core";
import { changeClientViewState, parseClientViewState } from "@gemologic/sheen-table/core";
import { deserializeState, parseTableState, serializeState } from "@gemologic/sheen-table/core";
import { changeTableState } from "@gemologic/sheen-table/core";
import { createTableSelection } from "@gemologic/sheen-table/core";
import { createClientExport } from "@gemologic/sheen-table/core";
import { selectClientRows } from "@gemologic/sheen-table/core";
import { createServerExport } from "@gemologic/sheen-table/core";
import { createCellEdit } from "@gemologic/sheen-table/core";
import { createRowIdentity, defineColumns } from "@gemologic/sheen-table/core";
import { createSavedViews, createTableUrlState } from "@gemologic/sheen-table/core";

const pagination: TablePagination = { pageIndex: 1, pageSize: 2 };
const rows = [{ id: "a" }, { id: "b" }, { id: "c" }];
assert.deepEqual(paginateClientRows(rows, pagination).rows, [rows[2]]);
assert.equal(paginateClientRows(rows, false).rows, rows);
assert.throws(() => resolvePagination("server"), /explicit pagination/);
assert.throws(() => assessServerPage(false, { rows: [rows[0]], total: 3 }), /complete/);
assert.deepEqual(assessServerPage({ pageIndex: 8, pageSize: 2 }, { rows: [], total: 3 }), { kind: "refetch", pagination: { pageIndex: 1, pageSize: 2 }, total: 3 });
assert.equal(assessServerPage(pagination, { rows: [], total: 0 }).kind, "accepted");
const initialState = { pagination: false } satisfies { pagination: TablePagination };
const controller = createTableRequests(async () => { throw new Error("Initial results must not dispatch a request"); }, { state: initialState, result: { rows, total: rows.length } });
assert.equal(controller.getSnapshot().accepted?.result.rows, rows);
assert.equal(controller.getSnapshot().pending, false);
controller.dispose();
assert.equal(controller.getSnapshot().accepted, null);
const columns = [{ id: "id", type: "text" }] satisfies FilterColumn[];
const filter = parseFilter({ kind: "text", column: "id", operator: "eq", value: "a" }, columns);
assert.deepEqual(deserializeFilter(serializeFilter(filter, columns), columns), filter);
const evaluation = { locale: "en-US", getValue: (row: { id: string }) => row.id };
const matches = compileFilter(filter, columns, evaluation);
assert.equal(matches({ id: "A" }), true);
assert.equal(matches({ id: "b" }), false);
const filtered = filterClientRows(rows, filter, columns, evaluation);
assert.deepEqual(filtered, [rows[0]]);
assert.equal(filtered[0], rows[0]);
const sorting = parseSorting([{ column: "id", direction: "desc" }], columns);
const sorted = sortClientRows(rows, sorting, columns, evaluation);
assert.deepEqual(sorted, [rows[2], rows[1], rows[0]]);
assert.equal(sorted[0], rows[2]);
const facets = countClientFacets(rows, [{ id: "id", type: "enum", options: ["a", "b", "c", "d"] }], evaluation);
assert.deepEqual(facets, [{ column: "id", options: [{ value: "a", count: 1 }, { value: "b", count: 1 }, { value: "c", count: 1 }, { value: "d", count: 0 }], missing: 0 }]);
assert.deepEqual(searchClientRows(rows, "A", { ...evaluation, columns: ["id"] }), [{ row: rows[0], rank: 0 }]);
const search = createDebouncedSearch(query => searchClientRows(rows, query, { ...evaluation, columns: ["id"] }), 0);
assert.equal(await search.request("b"), "accepted");
assert.equal(search.getSnapshot().accepted?.result[0]?.row, rows[1]);
search.dispose();
assert.equal(await search.request("a"), "disposed");
const initialSearch = createDebouncedSearch(() => { throw new Error("Initial search must not evaluate"); }, 0, { query: "all", result: rows });
assert.equal(initialSearch.getSnapshot().accepted?.result, rows);
assert.equal(initialSearch.getSnapshot().pending, false);
initialSearch.dispose();
const view = createClientView(rows, { search: "", filter, sorting, pagination: false }, { ...evaluation, searchColumns: ["id"], filterColumns: columns, sortColumns: columns });
assert.deepEqual(view.rows, [rows[0]]);
assert.equal(view.rows, view.view);
assert.equal(view.total, 1);
const schema = { filterColumns: columns, sortColumns: columns };
const queryState = parseClientViewState({ search: "", filter, sorting, pagination: { pageIndex: 3, pageSize: 20 } }, schema);
assert.deepEqual(changeClientViewState(queryState, { kind: "search", value: "new" }, schema).pagination, { pageIndex: 0, pageSize: 20 });
const tableSchema = { ...schema, columns: ["id"] };
const saved = parseTableState({ ...queryState, columns: [{ id: "id", visible: true, width: null, pin: false }] }, tableSchema);
assert.deepEqual(deserializeState(serializeState(saved, tableSchema), tableSchema), saved);
assert.equal(changeTableState(saved, { kind: "columnVisibility", column: "id", visible: false }, tableSchema).columns[0]?.visible, false);
const selection = createTableSelection(filter, columns);
selection.setLoadedIds(["a"]);
selection.selectLoaded();
assert.deepEqual(selection.getPayload(), { kind: "ids", ids: ["a"] });
selection.selectAllMatching();
selection.setSelected("a", false);
assert.deepEqual(selection.getPayload(), { kind: "query", filter, excluded: ["a"] });
const exported = createClientExport(rows, [{ id: "id", header: "ID", value: row => row.id }]);
assert.equal(exported.toCSV(), '"ID"\r\n"a"\r\n"b"\r\n"c"\r\n');
assert.deepEqual(JSON.parse(exported.toJSON()), rows);
assert.deepEqual(selectClientRows(rows, { kind: "ids", ids: ["c", "a"] }, { ...evaluation, filterColumns: columns, getRowId: row => row.id }), [rows[0], rows[2]]);
const unavailableExport = createServerExport(tableSchema);
assert.equal(unavailableExport.available, false);
assert.equal(await unavailableExport.request({ format: "csv", state: saved, selection: null }), "unavailable");
unavailableExport.dispose();
const cell = createCellEdit<string>("old", async request => ({ kind: "accepted", value: request.value }));
assert.equal(cell.begin(), true);
cell.setDraft("new");
assert.equal(await cell.commit(), "accepted");
assert.equal(cell.getSnapshot().committed, "new");
cell.dispose();
const brandedColumns = defineColumns<{ id: string }>([{ id: "id", header: "ID", accessor: row => row.id, filter: { type: "text" } }]);
assert.equal(Object.keys(brandedColumns).length, 0);
const rowIdentity = createRowIdentity<{ id: string }>(row => row.id);
const identified = rowIdentity.resolve(rows);
assert.deepEqual(identified.map(entry => entry.id), ["a", "b", "c"]);
assert.equal(identified[0]?.row, rows[0]);
assert.equal(typeof createTableUrlState, "function");
assert.equal(typeof createSavedViews, "function");
console.log("Isolated table pagination, filter evaluation/serialization, sorting, facets, search, and initial request-state exports passed");
