import { defineMeta } from "../../ui/src/metadata.ts";
import type { AdminAppProps } from "./AdminApp.tsx";

export default defineMeta<AdminAppProps>({
  name: "AdminApp", package: "@gemologic/sheen-patterns", category: "application", summary: "The Sheen application baseline with placement-safe chrome, scoped services, retained content, and responsive details.",
  props: {
    label: { description: "Accessible name for the primary content scrolling region." },
    documentTitle: { description: "Optional accepted-route document title. Requires an app-owned MetaProvider." },
    preset: { description: "Named deterministic placement configuration.", default: "standard", control: { kind: "select", values: ["standard", "workspace", "horizontal", "inspector"] } },
    appearance: { description: "Independent semantic chrome, navigation, and action treatments. Exact brand colors use the documented --sheen-admin-color-* aliases." },
    theme: { description: "Optional scoped theme, mode, accent, density, radius, motion, direction, and locale overrides. Omitted axes inherit; density alone defaults to comfortable." },
    placements: { description: "Per-zone validated overrides. A zone may occur at most once." },
    pathname: { description: "Accepted app pathname for native navigation matching." },
    router: { description: "Optional app-injected navigation and unsaved-change adapter." },
    product: { description: "Optional app-owned product identity." },
    workspace: { description: "Optional app-owned workspace selector model." },
    primaryNavigation: { description: "Optional app-owned primary navigation tree. Links may expose named sibling action menus without nesting controls inside destinations." },
    secondaryNavigation: { description: "Optional app-owned secondary navigation tree. Links may expose named sibling action menus without changing link semantics." },
    currentView: { description: "Optional breadcrumb or accepted current-view label." },
    globalSearch: { description: "Optional app-owned search control. Sheen does not perform the search." },
    actionGroups: { description: "Semantic primary, utility, and help action groups with native Button or Link behavior." },
    notifications: { description: "Optional app-owned notification model." },
    account: { description: "Optional app-owned account identity and menu. Sheen does not authenticate." },
    commandPalette: { description: "Optional scoped command sources, state, persistence, and error hooks." },
    details: { description: "Optional controlled or URL-backed details identity and its single content owner." },
    statusBar: { description: "Optional fixed application status content." },
    refreshing: { description: "Marks accepted page content busy without replacing or remounting it.", default: false },
    contentReady: { description: "Forwarded route readiness for pane-scroll restoration." },
    sidebarCollapsed: { description: "Controlled desktop icon-rail state. Phone navigation remains a full drawer." },
    defaultSidebarCollapsed: { description: "Server-resolved uncontrolled initial icon-rail state.", default: false },
    onSidebarCollapsedChange: { description: "Collapse proposals from the shell toggle and mod+/ shortcut." },
    sidebarPersistence: { description: "Explicit server-resolved initial preference plus app-owned save and safe error handling. No localStorage read occurs." },
    mobileSidebarOpen: { description: "Optional app-owned phone drawer state, independent of desktop collapse." },
    onMobileSidebarOpenChange: { description: "Phone drawer visibility proposals." },
    shortcutHelp: { description: "Enable the shared question-mark shortcut sheet and pending shortcut status.", default: true },
    development: { description: "Enable development-only shortcut diagnostics.", default: false },
    authorizationKey: { description: "Optional diagnostic boundary identity. Apps must clear unauthorized models and content synchronously when it changes." },
    class: { description: "Additional class on the low-level AppShell root." },
    children: { description: "Accepted page content. Background refresh keeps this owner mounted." },
  },
  tokens: ["--sheen-admin-color-canvas", "--sheen-admin-color-topbar", "--sheen-admin-color-sidebar", "--sheen-admin-color-details", "--sheen-admin-color-status", "--sheen-admin-color-nav-hover", "--sheen-admin-color-nav-active", "--sheen-admin-color-nav-active-fg", "--sheen-color-focus-ring"],
  a11y: { role: "banner, navigation, main, complementary, contentinfo, dialog, status", keyboard: ["Tab", "Shift+Tab", "ArrowLeft", "ArrowRight", "Home", "End", "Escape", "mod+k", "mod+/", "?"] },
  examples: [{
    title: "Standard admin baseline",
    imports: 'import { ThemeProvider } from "@gemologic/sheen";',
    code: '<ThemeProvider><AdminApp label="Operations" pathname="/orders" product={{ name: "Northstar", href: "/" }} primaryNavigation={{ id: "primary", label: "Primary", items: [{ kind: "link", id: "orders", label: "Orders", href: "/orders" }] }}><p>Application content</p></AdminApp></ThemeProvider>',
  }],
  composer: { allowedParentRegions: ["root"], acceptedChildRegions: ["topbar", "sidebar", "page-header", "toolbar", "main-grid", "details-panel", "status-bar", "overlays"], editableSafeProps: ["preset", "appearance", "placements"], fixtureFactory: "application", codeGenerationAdapter: "admin-document" },
  guidance: { do: ["Treat placements and appearance as stable server input; use themes and accents for global brand axes and admin aliases for shell-specific surfaces."], dont: ["Do not remount AdminApp during refresh or use it as a global arbitrary-content modal manager."] },
});
