import { defineMeta } from "@gemologic/sheen/metadata";
import type { DateTimePickerProps } from "./DateTimePicker.tsx";

export default defineMeta<DateTimePickerProps>({
  name: "DateTimePicker", package: "@gemologic/sheen-date", category: "date and time", summary: "A date, wall-time, and IANA-zone editor that resolves instants without hiding DST ambiguity.",
  props: {
    label: { description: "Required visible fieldset legend." }, value: { description: "App-owned Sheen DateTime instant, or null." }, defaultValue: { description: "Initial uncontrolled instant." }, onValueChange: { description: "Receives exact or explicitly disambiguated instants and clearing." }, onResolution: { description: "Observes every exact, ambiguous, or nonexistent wall-time resolution." }, timeZoneOptions: { description: "Explicit stable IANA zones passed to the zone combobox." }, timeZonePending: { description: "Retains accepted zone options while an app-owned refresh is in flight.", default: false }, timeZoneError: { description: "Safe app-owned zone request error." }, onTimeZoneRetry: { description: "Optional app retry action for a failed zone request." }, defaultTimeZone: { description: "Zone used by an empty draft, defaulting to UTC." }, defaultDate: { description: "Deterministic empty date placeholder." }, defaultTime: { description: "Deterministic empty wall-time placeholder." }, disambiguation: { description: "Policy for repeated or skipped local times; reject exposes an explicit choice.", default: "reject", control: { kind: "select", values: ["reject", "earlier", "later", "compatible"] } }, timeZoneChangeBehavior: { description: "Whether a zone change preserves the accepted instant or reinterprets the wall time.", default: "preserve-instant", control: { kind: "select", values: ["preserve-instant", "preserve-wall"] } }, locale: { description: "Explicit BCP 47 locale, defaulting to context." }, calendar: { description: "Optional calendar used only for date presentation and interaction." }, hourCycle: { description: "Explicit 12- or 24-hour cycle.", control: { kind: "select", values: [12, 24] } }, granularity: { description: "Smallest wall-time segment.", default: "minute", control: { kind: "select", values: ["minute", "second"] } }, name: { description: "Native form name for the ISO instant with bracketed IANA zone." }, form: { description: "Optional external form owner." }, description: { description: "Associated instructions." }, error: { description: "Associated app validation error." }, dateLabel: { description: "Localized label for the date subfield." }, timeLabel: { description: "Localized label for the wall-time subfield." }, timeZoneLabel: { description: "Localized label for the zone subfield." }, required: { description: "Marks all subfields required.", default: false }, disabled: { description: "Disables all subfields and projection.", default: false }, readOnly: { description: "Allows inspection while rejecting changes.", default: false },
  },
  tokens: ["--sheen-color-bg-raised", "--sheen-color-border-control", "--sheen-color-warning-border", "--sheen-color-focus-ring"],
  a11y: { role: "group, textbox, spinbuttons, combobox, alert", keyboard: ["Tab", "Shift+Tab", "Enter", "Space", "Escape", "Arrow keys", "PageUp", "PageDown", "Home", "End"] },
  examples: [{ title: "Maintenance start", code: '<DateTimePicker label="Maintenance start" name="startsAt" timeZoneOptions={[{ id: "UTC", label: "UTC" }, { id: "America/New_York", label: "New York" }]} defaultValue={createDateTime(1788897600000, createTimeZone("UTC"))} />' }],
  guidance: { do: ["Keep reject as the default when the app must distinguish repeated or skipped local times.", "Choose zone-change semantics for the application's domain."], dont: ["Do not silently substitute the browser timezone or accept an ambiguous wall time."] },
});
