// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixAdd, phosphorAdd } from "../generated/data/add.ts";

export const AddIcon = createStaticIcon("add", [radixAdd, phosphorAdd]);
export default AddIcon;
