// Generated by tools/build-icons.ts. Do not edit.
import { AddIcon } from "./add.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./AddIcon.meta.ts";

export const controls = metadata.props;
export default function AddIconDemo(props: StaticIconProps) { return <AddIcon {...props} />; }
