// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixArrowRight, phosphorArrowRight } from "../generated/data/arrow-right.ts";

export const ArrowRightIcon = createStaticIcon("arrowRight", [radixArrowRight, phosphorArrowRight]);
export default ArrowRightIcon;
