// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixArrowUp, phosphorArrowUp } from "../generated/data/arrow-up.ts";

export const ArrowUpIcon = createStaticIcon("arrowUp", [radixArrowUp, phosphorArrowUp]);
export default ArrowUpIcon;
