// Generated by tools/build-icons.ts. Do not edit.
import { ArrowRightIcon } from "./arrow-right.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./ArrowRightIcon.meta.ts";

export const controls = metadata.props;
export default function ArrowRightIconDemo(props: StaticIconProps) { return <ArrowRightIcon {...props} />; }
