// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixArrowDown, phosphorArrowDown } from "../generated/data/arrow-down.ts";

export const ArrowDownIcon = createStaticIcon("arrowDown", [radixArrowDown, phosphorArrowDown]);
export default ArrowDownIcon;
