// Generated by tools/build-icons.ts. Do not edit.
import { ArrowUpIcon } from "./arrow-up.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./ArrowUpIcon.meta.ts";

export const controls = metadata.props;
export default function ArrowUpIconDemo(props: StaticIconProps) { return <ArrowUpIcon {...props} />; }
