// Generated by tools/build-icons.ts. Do not edit.
import { ArrowDownIcon } from "./arrow-down.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./ArrowDownIcon.meta.ts";

export const controls = metadata.props;
export default function ArrowDownIconDemo(props: StaticIconProps) { return <ArrowDownIcon {...props} />; }
