// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixArrowLeft, phosphorArrowLeft } from "../generated/data/arrow-left.ts";

export const ArrowLeftIcon = createStaticIcon("arrowLeft", [radixArrowLeft, phosphorArrowLeft]);
export default ArrowLeftIcon;
