// Generated by tools/build-icons.ts. Do not edit.
import { ArrowLeftIcon } from "./arrow-left.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./ArrowLeftIcon.meta.ts";

export const controls = metadata.props;
export default function ArrowLeftIconDemo(props: StaticIconProps) { return <ArrowLeftIcon {...props} />; }
