// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixCalendar, phosphorCalendar } from "../generated/data/calendar.ts";

export const CalendarIcon = createStaticIcon("calendar", [radixCalendar, phosphorCalendar]);
export default CalendarIcon;
