// Generated by tools/build-icons.ts. Do not edit.
import { CalendarIcon } from "./calendar.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./CalendarIcon.meta.ts";

export const controls = metadata.props;
export default function CalendarIconDemo(props: StaticIconProps) { return <CalendarIcon {...props} />; }
