// Generated by tools/build-icons.ts. Do not edit.
import { CheckIcon } from "./check.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./CheckIcon.meta.ts";

export const controls = metadata.props;
export default function CheckIconDemo(props: StaticIconProps) { return <CheckIcon {...props} />; }
