// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixCheck, phosphorCheck } from "../generated/data/check.ts";

export const CheckIcon = createStaticIcon("check", [radixCheck, phosphorCheck]);
export default CheckIcon;
