// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixChevronLeft, phosphorChevronLeft } from "../generated/data/chevron-left.ts";

export const ChevronLeftIcon = createStaticIcon("chevronLeft", [radixChevronLeft, phosphorChevronLeft]);
export default ChevronLeftIcon;
