// Generated by tools/build-icons.ts. Do not edit.
import { ChevronRightIcon } from "./chevron-right.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./ChevronRightIcon.meta.ts";

export const controls = metadata.props;
export default function ChevronRightIconDemo(props: StaticIconProps) { return <ChevronRightIcon {...props} />; }
