// Generated by tools/build-icons.ts. Do not edit.
import { ChevronDownIcon } from "./chevron-down.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./ChevronDownIcon.meta.ts";

export const controls = metadata.props;
export default function ChevronDownIconDemo(props: StaticIconProps) { return <ChevronDownIcon {...props} />; }
