// Generated by tools/build-icons.ts. Do not edit.
import { ChevronUpIcon } from "./chevron-up.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./ChevronUpIcon.meta.ts";

export const controls = metadata.props;
export default function ChevronUpIconDemo(props: StaticIconProps) { return <ChevronUpIcon {...props} />; }
