// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixChevronRight, phosphorChevronRight } from "../generated/data/chevron-right.ts";

export const ChevronRightIcon = createStaticIcon("chevronRight", [radixChevronRight, phosphorChevronRight]);
export default ChevronRightIcon;
