// Generated by tools/build-icons.ts. Do not edit.
import { ChevronLeftIcon } from "./chevron-left.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./ChevronLeftIcon.meta.ts";

export const controls = metadata.props;
export default function ChevronLeftIconDemo(props: StaticIconProps) { return <ChevronLeftIcon {...props} />; }
