// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixChevronDown, phosphorChevronDown } from "../generated/data/chevron-down.ts";

export const ChevronDownIcon = createStaticIcon("chevronDown", [radixChevronDown, phosphorChevronDown]);
export default ChevronDownIcon;
