// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixChevronUp, phosphorChevronUp } from "../generated/data/chevron-up.ts";

export const ChevronUpIcon = createStaticIcon("chevronUp", [radixChevronUp, phosphorChevronUp]);
export default ChevronUpIcon;
