// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixClock, phosphorClock } from "../generated/data/clock.ts";

export const ClockIcon = createStaticIcon("clock", [radixClock, phosphorClock]);
export default ClockIcon;
