// Generated by tools/build-icons.ts. Do not edit.
import { ClockIcon } from "./clock.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./ClockIcon.meta.ts";

export const controls = metadata.props;
export default function ClockIconDemo(props: StaticIconProps) { return <ClockIcon {...props} />; }
