// Generated by tools/build-icons.ts. Do not edit.
import { CloseIcon } from "./close.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./CloseIcon.meta.ts";

export const controls = metadata.props;
export default function CloseIconDemo(props: StaticIconProps) { return <CloseIcon {...props} />; }
