// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixClose, phosphorClose } from "../generated/data/close.ts";

export const CloseIcon = createStaticIcon("close", [radixClose, phosphorClose]);
export default CloseIcon;
