// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixCopy, phosphorCopy } from "../generated/data/copy.ts";

export const CopyIcon = createStaticIcon("copy", [radixCopy, phosphorCopy]);
export default CopyIcon;
