// Generated by tools/build-icons.ts. Do not edit.
import { CopyIcon } from "./copy.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./CopyIcon.meta.ts";

export const controls = metadata.props;
export default function CopyIconDemo(props: StaticIconProps) { return <CopyIcon {...props} />; }
