// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixDownload, phosphorDownload } from "../generated/data/download.ts";

export const DownloadIcon = createStaticIcon("download", [radixDownload, phosphorDownload]);
export default DownloadIcon;
