// Generated by tools/build-icons.ts. Do not edit.
import { DownloadIcon } from "./download.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./DownloadIcon.meta.ts";

export const controls = metadata.props;
export default function DownloadIconDemo(props: StaticIconProps) { return <DownloadIcon {...props} />; }
