// Generated by tools/build-icons.ts. Do not edit.
import { EditIcon } from "./edit.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./EditIcon.meta.ts";

export const controls = metadata.props;
export default function EditIconDemo(props: StaticIconProps) { return <EditIcon {...props} />; }
