// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixEdit, phosphorEdit } from "../generated/data/edit.ts";

export const EditIcon = createStaticIcon("edit", [radixEdit, phosphorEdit]);
export default EditIcon;
