// Generated by tools/build-icons.ts. Do not edit.
import { ErrorIcon } from "./error.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./ErrorIcon.meta.ts";

export const controls = metadata.props;
export default function ErrorIconDemo(props: StaticIconProps) { return <ErrorIcon {...props} />; }
