// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixError, phosphorError } from "../generated/data/error.ts";

export const ErrorIcon = createStaticIcon("error", [radixError, phosphorError]);
export default ErrorIcon;
