// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixExternalLink, phosphorExternalLink } from "../generated/data/external-link.ts";

export const ExternalLinkIcon = createStaticIcon("externalLink", [radixExternalLink, phosphorExternalLink]);
export default ExternalLinkIcon;
