// Generated by tools/build-icons.ts. Do not edit.
import { ExternalLinkIcon } from "./external-link.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./ExternalLinkIcon.meta.ts";

export const controls = metadata.props;
export default function ExternalLinkIconDemo(props: StaticIconProps) { return <ExternalLinkIcon {...props} />; }
