// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixFilter, phosphorFilter } from "../generated/data/filter.ts";

export const FilterIcon = createStaticIcon("filter", [radixFilter, phosphorFilter]);
export default FilterIcon;
