// Generated by tools/build-icons.ts. Do not edit.
import { FilterIcon } from "./filter.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./FilterIcon.meta.ts";

export const controls = metadata.props;
export default function FilterIconDemo(props: StaticIconProps) { return <FilterIcon {...props} />; }
