// Generated by tools/build-icons.ts. Do not edit.
import { HiddenIcon } from "./hidden.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./HiddenIcon.meta.ts";

export const controls = metadata.props;
export default function HiddenIconDemo(props: StaticIconProps) { return <HiddenIcon {...props} />; }
