// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixHidden, phosphorHidden } from "../generated/data/hidden.ts";

export const HiddenIcon = createStaticIcon("hidden", [radixHidden, phosphorHidden]);
export default HiddenIcon;
