// Generated by tools/build-icons.ts. Do not edit.
import { HomeIcon } from "./home.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./HomeIcon.meta.ts";

export const controls = metadata.props;
export default function HomeIconDemo(props: StaticIconProps) { return <HomeIcon {...props} />; }
