// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixHome, phosphorHome } from "../generated/data/home.ts";

export const HomeIcon = createStaticIcon("home", [radixHome, phosphorHome]);
export default HomeIcon;
