// Generated by tools/build-icons.ts. Do not edit.
export default Object.freeze({
  name: "InboxIcon", package: "@gemologic/sheen-icons", category: "icons",
  summary: "The statically importable inbox semantic icon with Radix and Phosphor artwork.",
  props: {
    size: { description: "Token-sized icon dimensions.", default: "md", control: { kind: "select", values: ["sm", "md", "lg"] } },
    tone: { description: "Muted at rest or inherited from an interactive parent.", default: "muted", control: { kind: "select", values: ["muted", "inherit"] } },
    decorative: { description: "Decorative by default; set false together with a nonempty label for meaningful imagery.", default: true, control: { kind: "boolean" } },
    label: { description: "Required accessible name when decorative is false.", control: { kind: "text" } },
  },
  tokens: ["--sheen-icon-size-sm", "--sheen-icon-size-md", "--sheen-icon-size-lg", "--sheen-color-fg-muted"],
  a11y: { role: "img when meaningful; hidden when decorative", keyboard: [] },
  examples: [{ title: "inbox action", code: "<InboxIcon decorative={false} label=\"inbox\" />" }],
  guidance: { do: ["Use semantic names so themes can switch artwork without changing application code."], dont: ["Do not place an unlabeled meaningful icon where text is required."] },
});
