// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixInbox, phosphorInbox } from "../generated/data/inbox.ts";

export const InboxIcon = createStaticIcon("inbox", [radixInbox, phosphorInbox]);
export default InboxIcon;
