// Generated by tools/build-icons.ts. Do not edit.
import { InboxIcon } from "./inbox.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./InboxIcon.meta.ts";

export const controls = metadata.props;
export default function InboxIconDemo(props: StaticIconProps) { return <InboxIcon {...props} />; }
