// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixInfo, phosphorInfo } from "../generated/data/info.ts";

export const InfoIcon = createStaticIcon("info", [radixInfo, phosphorInfo]);
export default InfoIcon;
