// Generated by tools/build-icons.ts. Do not edit.
import { InfoIcon } from "./info.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./InfoIcon.meta.ts";

export const controls = metadata.props;
export default function InfoIconDemo(props: StaticIconProps) { return <InfoIcon {...props} />; }
