// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixLock, phosphorLock } from "../generated/data/lock.ts";

export const LockIcon = createStaticIcon("lock", [radixLock, phosphorLock]);
export default LockIcon;
