// Generated by tools/build-icons.ts. Do not edit.
import { LockIcon } from "./lock.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./LockIcon.meta.ts";

export const controls = metadata.props;
export default function LockIconDemo(props: StaticIconProps) { return <LockIcon {...props} />; }
