// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixMenu, phosphorMenu } from "../generated/data/menu.ts";

export const MenuIcon = createStaticIcon("menu", [radixMenu, phosphorMenu]);
export default MenuIcon;
