// Generated by tools/build-icons.ts. Do not edit.
import { MenuIcon } from "./menu.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./MenuIcon.meta.ts";

export const controls = metadata.props;
export default function MenuIconDemo(props: StaticIconProps) { return <MenuIcon {...props} />; }
