// Generated by tools/build-icons.ts. Do not edit.
import { MoreVerticalIcon } from "./more-vertical.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./MoreVerticalIcon.meta.ts";

export const controls = metadata.props;
export default function MoreVerticalIconDemo(props: StaticIconProps) { return <MoreVerticalIcon {...props} />; }
