// Generated by tools/build-icons.ts. Do not edit.
import { MoreHorizontalIcon } from "./more-horizontal.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./MoreHorizontalIcon.meta.ts";

export const controls = metadata.props;
export default function MoreHorizontalIconDemo(props: StaticIconProps) { return <MoreHorizontalIcon {...props} />; }
