// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixMoreHorizontal, phosphorMoreHorizontal } from "../generated/data/more-horizontal.ts";

export const MoreHorizontalIcon = createStaticIcon("moreHorizontal", [radixMoreHorizontal, phosphorMoreHorizontal]);
export default MoreHorizontalIcon;
