// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixMoreVertical, phosphorMoreVertical } from "../generated/data/more-vertical.ts";

export const MoreVerticalIcon = createStaticIcon("moreVertical", [radixMoreVertical, phosphorMoreVertical]);
export default MoreVerticalIcon;
