// Generated by tools/build-icons.ts. Do not edit.
import { NotificationsIcon } from "./notifications.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./NotificationsIcon.meta.ts";

export const controls = metadata.props;
export default function NotificationsIconDemo(props: StaticIconProps) { return <NotificationsIcon {...props} />; }
