// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixNotifications, phosphorNotifications } from "../generated/data/notifications.ts";

export const NotificationsIcon = createStaticIcon("notifications", [radixNotifications, phosphorNotifications]);
export default NotificationsIcon;
