// Generated by tools/build-icons.ts. Do not edit.
import { RefreshIcon } from "./refresh.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./RefreshIcon.meta.ts";

export const controls = metadata.props;
export default function RefreshIconDemo(props: StaticIconProps) { return <RefreshIcon {...props} />; }
