// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixRefresh, phosphorRefresh } from "../generated/data/refresh.ts";

export const RefreshIcon = createStaticIcon("refresh", [radixRefresh, phosphorRefresh]);
export default RefreshIcon;
