// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixRemove, phosphorRemove } from "../generated/data/remove.ts";

export const RemoveIcon = createStaticIcon("remove", [radixRemove, phosphorRemove]);
export default RemoveIcon;
