// Generated by tools/build-icons.ts. Do not edit.
import { RemoveIcon } from "./remove.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./RemoveIcon.meta.ts";

export const controls = metadata.props;
export default function RemoveIconDemo(props: StaticIconProps) { return <RemoveIcon {...props} />; }
