// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixSearch, phosphorSearch } from "../generated/data/search.ts";

export const SearchIcon = createStaticIcon("search", [radixSearch, phosphorSearch]);
export default SearchIcon;
