// Generated by tools/build-icons.ts. Do not edit.
import { SearchIcon } from "./search.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./SearchIcon.meta.ts";

export const controls = metadata.props;
export default function SearchIconDemo(props: StaticIconProps) { return <SearchIcon {...props} />; }
