// Generated by tools/build-icons.ts. Do not edit.
import { SettingsIcon } from "./settings.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./SettingsIcon.meta.ts";

export const controls = metadata.props;
export default function SettingsIconDemo(props: StaticIconProps) { return <SettingsIcon {...props} />; }
