// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixSettings, phosphorSettings } from "../generated/data/settings.ts";

export const SettingsIcon = createStaticIcon("settings", [radixSettings, phosphorSettings]);
export default SettingsIcon;
