// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixSortDescending, phosphorSortDescending } from "../generated/data/sort-descending.ts";

export const SortDescendingIcon = createStaticIcon("sortDescending", [radixSortDescending, phosphorSortDescending]);
export default SortDescendingIcon;
