// Generated by tools/build-icons.ts. Do not edit.
import { SortDescendingIcon } from "./sort-descending.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./SortDescendingIcon.meta.ts";

export const controls = metadata.props;
export default function SortDescendingIconDemo(props: StaticIconProps) { return <SortDescendingIcon {...props} />; }
