// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixSortAscending, phosphorSortAscending } from "../generated/data/sort-ascending.ts";

export const SortAscendingIcon = createStaticIcon("sortAscending", [radixSortAscending, phosphorSortAscending]);
export default SortAscendingIcon;
