// Generated by tools/build-icons.ts. Do not edit.
import { SortAscendingIcon } from "./sort-ascending.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./SortAscendingIcon.meta.ts";

export const controls = metadata.props;
export default function SortAscendingIconDemo(props: StaticIconProps) { return <SortAscendingIcon {...props} />; }
