// Generated by tools/build-icons.ts. Do not edit.
import { SuccessIcon } from "./success.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./SuccessIcon.meta.ts";

export const controls = metadata.props;
export default function SuccessIconDemo(props: StaticIconProps) { return <SuccessIcon {...props} />; }
