// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixSuccess, phosphorSuccess } from "../generated/data/success.ts";

export const SuccessIcon = createStaticIcon("success", [radixSuccess, phosphorSuccess]);
export default SuccessIcon;
