// Generated by tools/build-icons.ts. Do not edit.
import { TrashIcon } from "./trash.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./TrashIcon.meta.ts";

export const controls = metadata.props;
export default function TrashIconDemo(props: StaticIconProps) { return <TrashIcon {...props} />; }
