// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixTrash, phosphorTrash } from "../generated/data/trash.ts";

export const TrashIcon = createStaticIcon("trash", [radixTrash, phosphorTrash]);
export default TrashIcon;
