// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixUnlock, phosphorUnlock } from "../generated/data/unlock.ts";

export const UnlockIcon = createStaticIcon("unlock", [radixUnlock, phosphorUnlock]);
export default UnlockIcon;
