// Generated by tools/build-icons.ts. Do not edit.
import { UnlockIcon } from "./unlock.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./UnlockIcon.meta.ts";

export const controls = metadata.props;
export default function UnlockIconDemo(props: StaticIconProps) { return <UnlockIcon {...props} />; }
