// Generated by tools/build-icons.ts. Do not edit.
import { UploadIcon } from "./upload.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./UploadIcon.meta.ts";

export const controls = metadata.props;
export default function UploadIconDemo(props: StaticIconProps) { return <UploadIcon {...props} />; }
