// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixUpload, phosphorUpload } from "../generated/data/upload.ts";

export const UploadIcon = createStaticIcon("upload", [radixUpload, phosphorUpload]);
export default UploadIcon;
