// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixUsers, phosphorUsers } from "../generated/data/users.ts";

export const UsersIcon = createStaticIcon("users", [radixUsers, phosphorUsers]);
export default UsersIcon;
