// Generated by tools/build-icons.ts. Do not edit.
import { UsersIcon } from "./users.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./UsersIcon.meta.ts";

export const controls = metadata.props;
export default function UsersIconDemo(props: StaticIconProps) { return <UsersIcon {...props} />; }
