// Generated by tools/build-icons.ts. Do not edit.
import { UserIcon } from "./user.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./UserIcon.meta.ts";

export const controls = metadata.props;
export default function UserIconDemo(props: StaticIconProps) { return <UserIcon {...props} />; }
