// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixUser, phosphorUser } from "../generated/data/user.ts";

export const UserIcon = createStaticIcon("user", [radixUser, phosphorUser]);
export default UserIcon;
