// Generated by tools/build-icons.ts. Do not edit.
import { VisibleIcon } from "./visible.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./VisibleIcon.meta.ts";

export const controls = metadata.props;
export default function VisibleIconDemo(props: StaticIconProps) { return <VisibleIcon {...props} />; }
