// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixVisible, phosphorVisible } from "../generated/data/visible.ts";

export const VisibleIcon = createStaticIcon("visible", [radixVisible, phosphorVisible]);
export default VisibleIcon;
