// Generated by tools/build-icons.ts. Do not edit.
import { WarningIcon } from "./warning.tsx";
import type { StaticIconProps } from "../runtime.tsx";
import metadata from "./WarningIcon.meta.ts";

export const controls = metadata.props;
export default function WarningIconDemo(props: StaticIconProps) { return <WarningIcon {...props} />; }
