// Generated by tools/build-icons.ts. Do not edit.
import { createStaticIcon } from "../runtime.tsx";
import { radixWarning, phosphorWarning } from "../generated/data/warning.ts";

export const WarningIcon = createStaticIcon("warning", [radixWarning, phosphorWarning]);
export default WarningIcon;
