import { mkdir, readdir, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import phosphor from "../packages/icons/node_modules/@iconify-json/ph/icons.json" with { type: "json" };
import radix from "../packages/icons/node_modules/@iconify-json/radix-icons/icons.json" with { type: "json" };
import { iconRegistry } from "../packages/icons/src/registry.ts";
import type { IconName, IconSetName } from "../packages/icons/src/registry.ts";

interface RawIcon { readonly body: string; readonly width?: number; readonly height?: number }
interface RawCollection { readonly width?: number; readonly height?: number; readonly icons: Readonly<Record<string, RawIcon>> }

const collections: Readonly<Record<IconSetName, RawCollection>> = { radix, phosphor };
const root = fileURLToPath(new URL("../packages/icons/src/", import.meta.url));
const iconsRoot = join(root, "icons");
const generatedRoot = join(root, "generated");
const dataRoot = join(generatedRoot, "data");

function fileName(name: IconName): string { return name.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`); }
function componentName(name: IconName): string { return `${name.slice(0, 1).toUpperCase()}${name.slice(1)}Icon`; }
function identifier(set: IconSetName, name: IconName): string { return `${set}${name.slice(0, 1).toUpperCase()}${name.slice(1)}`; }

function data(set: IconSetName, name: IconName): { readonly set: IconSetName; readonly body: string; readonly width: number; readonly height: number } {
  const collection = collections[set];
  const sourceName = iconRegistry[name][set];
  const icon = collection.icons[sourceName];
  if (!icon) throw new Error(`${name}/${set} maps to missing ${sourceName}`);
  if (!icon.body.trim() || /<script|\son[a-z]+\s*=|\shref\s*=/i.test(icon.body)) throw new Error(`${name}/${set} contains unsafe SVG markup`);
  const width = icon.width ?? collection.width;
  const height = icon.height ?? collection.height;
  if (!Number.isFinite(width) || !Number.isFinite(height) || !width || !height) throw new Error(`${name}/${set} has invalid dimensions`);
  return { set, body: icon.body, width, height };
}

const names = Object.keys(iconRegistry).filter((name): name is IconName => Object.hasOwn(iconRegistry, name));
await mkdir(iconsRoot, { recursive: true });
await mkdir(generatedRoot, { recursive: true });
await mkdir(dataRoot, { recursive: true });
const expected = new Set(names.flatMap(name => [`${fileName(name)}.tsx`, `${componentName(name)}.meta.ts`, `${componentName(name)}.demo.tsx`]));
for (const entry of await readdir(iconsRoot, { withFileTypes: true })) if (entry.isFile() && !expected.has(entry.name)) await unlink(join(iconsRoot, entry.name));
const expectedData = new Set(names.map(name => `${fileName(name)}.ts`));
for (const entry of await readdir(dataRoot, { withFileTypes: true })) if (entry.isFile() && !expectedData.has(entry.name)) await unlink(join(dataRoot, entry.name));

const catalogImports: string[] = [];
const records: string[] = [];
const exports: string[] = [];
const modules: Promise<void>[] = [];
for (const name of names) {
  const values = (["radix", "phosphor"] satisfies IconSetName[]).map(set => data(set, name));
  const dataIdentifiers = values.map(value => identifier(value.set, name));
  records.push(`  ${JSON.stringify(name)}: Object.freeze([${values.map(value => identifier(value.set, name)).join(", ")}]),`);
  const component = componentName(name), file = fileName(name);
  catalogImports.push(`import { ${dataIdentifiers.join(", ")} } from "./data/${file}.ts";`);
  exports.push(`export { ${component} } from "../icons/${file}.tsx";`);
  modules.push(writeFile(join(dataRoot, `${file}.ts`), `// Generated by tools/build-icons.ts. Do not edit.\nimport type { IconData } from "../../runtime.tsx";\n\n${values.map(value => `export const ${identifier(value.set, name)} = Object.freeze(${JSON.stringify(value)}) satisfies IconData;`).join("\n")}\n`));
  modules.push(writeFile(join(iconsRoot, `${file}.tsx`), `// Generated by tools/build-icons.ts. Do not edit.\nimport { createStaticIcon } from "../runtime.tsx";\nimport { ${values.map(value => identifier(value.set, name)).join(", ")} } from "../generated/data/${file}.ts";\n\nexport const ${component} = createStaticIcon(${JSON.stringify(name)}, [${values.map(value => identifier(value.set, name)).join(", ")}]);\nexport default ${component};\n`));
  modules.push(writeFile(join(iconsRoot, `${component}.meta.ts`), `// Generated by tools/build-icons.ts. Do not edit.\nexport default Object.freeze({\n  name: ${JSON.stringify(component)}, package: "@gemologic/sheen-icons", category: "icons",\n  summary: ${JSON.stringify(`The statically importable ${name} semantic icon with Radix and Phosphor artwork.`)},\n  props: {\n    size: { description: "Token-sized icon dimensions.", default: "md", control: { kind: "select", values: ["sm", "md", "lg"] } },\n    tone: { description: "Muted at rest or inherited from an interactive parent.", default: "muted", control: { kind: "select", values: ["muted", "inherit"] } },\n    decorative: { description: "Decorative by default; set false together with a nonempty label for meaningful imagery.", default: true, control: { kind: "boolean" } },\n    label: { description: "Required accessible name when decorative is false.", control: { kind: "text" } },\n  },\n  tokens: ["--sheen-icon-size-sm", "--sheen-icon-size-md", "--sheen-icon-size-lg", "--sheen-color-fg-muted"],\n  a11y: { role: "img when meaningful; hidden when decorative", keyboard: [] },\n  examples: [{ title: ${JSON.stringify(`${name} action`)}, code: ${JSON.stringify(`<${component} decorative={false} label=${JSON.stringify(name)} />`)} }],\n  guidance: { do: ["Use semantic names so themes can switch artwork without changing application code."], dont: ["Do not place an unlabeled meaningful icon where text is required."] },\n});\n`));
  modules.push(writeFile(join(iconsRoot, `${component}.demo.tsx`), `// Generated by tools/build-icons.ts. Do not edit.\nimport { ${component} } from "./${file}.tsx";\nimport type { StaticIconProps } from "../runtime.tsx";\nimport metadata from "./${component}.meta.ts";\n\nexport const controls = metadata.props;\nexport default function ${component}Demo(props: StaticIconProps) { return <${component} {...props} />; }\n`));
}

await Promise.all([
  ...modules,
  writeFile(join(generatedRoot, "catalog.ts"), `// Generated by tools/build-icons.ts. Do not edit.\nimport type { IconData } from "../runtime.tsx";\nimport type { IconName } from "../registry.ts";\n${catalogImports.join("\n")}\n\nexport const iconData = Object.freeze({\n${records.join("\n")}\n}) satisfies Readonly<Record<IconName, readonly IconData[]>>;\n`),
  writeFile(join(generatedRoot, "icons.ts"), `// Generated by tools/build-icons.ts. Do not edit.\n${exports.join("\n")}\n`),
]);
console.log(`Generated ${names.length} semantic icons across Radix and Phosphor`);
