import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { createComposerFixtures, defaultComposerDocument } from "../apps/loupe/src/composer/fixtures.ts";
import { generateComposerTsx } from "../apps/loupe/src/composer/generator.ts";

const root = fileURLToPath(new URL("../", import.meta.url));
const target = join(root, "apps", "loupe", "src", "generated");
const fixtures = createComposerFixtures("northstar-v1");

await mkdir(target, { recursive: true });
await writeFile(join(target, "composer-self-contained.tsx"), `// Generated by tools/build-composer-fixtures.ts. Do not edit by hand.\n${generateComposerTsx(defaultComposerDocument, fixtures, "self-contained")}`);
await writeFile(join(target, "composer-structure-only.tsx"), `// Generated by tools/build-composer-fixtures.ts. Do not edit by hand.\n${generateComposerTsx(defaultComposerDocument, fixtures, "structure-only")}`);

console.log("Generated deterministic Composer self-contained and structure-only TSX fixtures");
