import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { createComposerFixtures, defaultComposerDocument } from "../apps/loupe/src/composer/fixtures.ts";
import { generateComposerTsx } from "../apps/loupe/src/composer/generator.ts";

const generatedHeader = "// Generated by tools/build-composer-fixtures.ts. Do not edit by hand.\n";
const fixtures = createComposerFixtures("northstar-v1");

async function generatedFile(name: string): Promise<string> {
  return readFile(fileURLToPath(new URL(`../apps/loupe/src/generated/${name}`, import.meta.url)), "utf8");
}

describe("Composer TSX generation", () => {
  it("matches both committed deterministic fixtures", async () => {
    expect(await generatedFile("composer-self-contained.tsx")).toBe(`${generatedHeader}${generateComposerTsx(defaultComposerDocument, fixtures, "self-contained")}`);
    expect(await generatedFile("composer-structure-only.tsx")).toBe(`${generatedHeader}${generateComposerTsx(defaultComposerDocument, fixtures, "structure-only")}`);
  });

  it("uses only public package imports and emits no runtime Composer or drag dependency", () => {
    for (const mode of ["self-contained", "structure-only"] as const) {
      const source = generateComposerTsx(defaultComposerDocument, fixtures, mode);
      expect(source).not.toMatch(/(?:composer|pragmatic-drag-and-drop|__unsafe_|style=)/u);
      expect(source).toContain('from "@gemologic/sheen"');
      expect(source).toContain('from "@gemologic/sheen-patterns/admin"');
      expect(source).toContain('from "@gemologic/sheen-table"');
      expect(source).toContain('from "@gemologic/sheen-charts/time-series"');
    }
  });

  it("keeps preview-only axes out of generated application structure", () => {
    const source = generateComposerTsx(defaultComposerDocument, fixtures, "self-contained");
    expect(source).not.toContain("viewport");
    expect(source).not.toContain("data-sheen-theme");
    expect(source).toContain('preset="standard"');
    expect(source).toContain('appearance={{"chrome":"layered","navigation":"subtle","actions":"quiet"}}');
  });
});
