import { mkdir, readdir, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { Node, Project, ScriptKind } from "ts-morph";
import type { ComponentMetadata } from "../packages/ui/src/metadata.ts";
import type { ManifestProp } from "./metadata.ts";

export interface LoupeDocSource {
  readonly metadata: ComponentMetadata;
  readonly props: Readonly<Record<string, ManifestProp>>;
  readonly packageName: string;
  readonly runtimeExports: readonly string[];
  readonly source: string;
}

function scalar(value: string | number | boolean | null): string {
  const serialized = JSON.stringify(value);
  if (serialized === undefined) throw new Error("Playground values must be JSON scalars");
  return serialized;
}

function controlExpression(name: string, prop: ManifestProp, variable: string): string {
  const control = prop.control;
  if (!control) throw new Error(`${name} has no playground control`);
  if (control.kind === "select") {
    const conditions = control.values.map(value => `${variable} === ${scalar(value)}`).join(" || ");
    return `${conditions} ? ${variable} : undefined`;
  }
  if (control.kind === "boolean") return `typeof ${variable} === "boolean" ? ${variable} : undefined`;
  return `typeof ${variable} === "string" ? ${variable} : undefined`;
}

function insertionOffset(name: string, code: string): number | null {
  const prefix = "const preview = () => (";
  const project = new Project({ useInMemoryFileSystem: true });
  const source = project.createSourceFile("preview.tsx", `${prefix}${code});`, { scriptKind: ScriptKind.TSX });
  const target = source.getDescendants().find(node =>
    (Node.isJsxOpeningElement(node) || Node.isJsxSelfClosingElement(node)) && node.getTagNameNode().getText() === name
  );
  if (!target) return null;
  const closingLength = Node.isJsxSelfClosingElement(target) ? 2 : 1;
  return target.getEnd() - closingLength - prefix.length;
}

function generatedModule(source: LoupeDocSource): string {
  const { metadata } = source;
  const first = metadata.examples[0];
  if (!first) throw new Error(`${metadata.name} requires an example`);
  const offset = insertionOffset(metadata.name, first.code);
  const controls = Object.entries(source.props).filter(([, prop]) => !prop.inherited && prop.control);
  const supportsControls = offset !== null && controls.length > 0;
  const defaults = Object.fromEntries(controls.flatMap(([name, prop]) => "default" in prop ? [[name, prop.default]] : []));
  const values = controls.map(([name, prop], index) => `      const value${index} = currentValues[${JSON.stringify(name)}];
      const controlled${index} = ${controlExpression(name, prop, `value${index}`)};`).join("\n");
  const controlled = controls.map(([name], index) => `        ...(controlled${index} === undefined ? {} : { ${JSON.stringify(name)}: controlled${index} })`).join(",\n");
  const playgroundCode = offset === null ? first.code : `${first.code.slice(0, offset)} {...controlledProps}${first.code.slice(offset)}`;
  const exampleImports = [...new Set(metadata.examples.flatMap(example => example.imports ? [example.imports] : []))];
  const examples = metadata.examples.map((example, index) => `    {
      title: ${JSON.stringify(example.title)},
      code: ${JSON.stringify(example.code)},
      render: function Example${index}() {
        ${example.setup ?? ""}
        return (${example.code});
      },
    }`).join(",\n");
  const variants = supportsControls ? controls.flatMap(([name, prop]) => prop.control?.kind === "select" ? prop.control.values.map(value => ({
    label: `${name}: ${String(value)}`,
    values: { ...defaults, [name]: value },
  })) : []).map(variant => `    { label: ${JSON.stringify(variant.label)}, values: Object.freeze(${JSON.stringify(variant.values)}) }`).join(",\n") : "";
  const playground = supportsControls ? `function Playground(props: { readonly values: Readonly<Record<string, PlaygroundValue>> }) {
  return <Show keyed when={props.values}>{currentValues => {
${first.setup ? `    ${first.setup}\n` : ""}${values}
    const controlledProps = {
${controlled}
    } satisfies Partial<ComponentProps<typeof ${metadata.name}>>;
    return (${playgroundCode});
  }}</Show>;
}` : `function Playground() {
${first.setup ? `  ${first.setup}\n` : ""}  return (${first.code});
}`;

  return `// Generated by tools/build-manifest.ts. Do not edit.
import { Show } from "solid-js";
import type { ComponentProps } from "solid-js";
import { ${source.runtimeExports.join(", ")} } from ${JSON.stringify(source.packageName)};
${exampleImports.join("\n")}
import type { ComponentExampleModule, PlaygroundValue } from "./index.ts";

${playground}

export const exampleModule = {
  defaults: Object.freeze(${JSON.stringify(defaults)}),
  controlsSupported: ${supportsControls},
  playgroundTemplate: ${JSON.stringify(first.code)},
  codeInsertionOffset: ${offset === null ? "null" : offset},
  playground: Playground,
  examples: Object.freeze([
${examples}
  ]),
  variants: Object.freeze([
${variants}
  ]),
} satisfies ComponentExampleModule;
`;
}

function generatedIndex(sources: readonly LoupeDocSource[]): string {
  const imports = sources.map(source => `import { exampleModule as ${source.metadata.name}Examples } from "./${source.metadata.name}.tsx";`).join("\n");
  const entries = sources.map(source => `  ${JSON.stringify(source.metadata.name)}: ${source.metadata.name}Examples,`).join("\n");
  return `// Generated by tools/build-manifest.ts. Do not edit.
import type { Component, JSX } from "solid-js";
${imports}

export type PlaygroundValue = string | number | boolean | null;
export interface ComponentExample {
  readonly title: string;
  readonly code: string;
  readonly render: Component;
}
export interface ComponentVariant {
  readonly label: string;
  readonly values: Readonly<Record<string, PlaygroundValue>>;
}
export interface ComponentExampleModule {
  readonly defaults: Readonly<Record<string, PlaygroundValue>>;
  readonly controlsSupported: boolean;
  readonly playgroundTemplate: string;
  readonly codeInsertionOffset: number | null;
  readonly playground: Component<{ readonly values: Readonly<Record<string, PlaygroundValue>> }>;
  readonly examples: readonly ComponentExample[];
  readonly variants: readonly ComponentVariant[];
}

export const componentExamples: Readonly<Record<string, ComponentExampleModule>> = Object.freeze({
${entries}
});

export type ComponentPreview = () => JSX.Element;
`;
}

function generatedDocs(sources: readonly LoupeDocSource[]): string {
  const docs = sources.map(source => ({
    name: source.metadata.name,
    package: source.metadata.package,
    category: source.metadata.category,
    summary: source.metadata.summary,
    props: Object.entries(source.props).filter(([, prop]) => !prop.inherited).map(([name, prop]) => ({
      name,
      description: prop.description,
      type: prop.type,
      required: prop.required,
      ...("default" in prop ? { default: prop.default } : {}),
      ...(prop.control ? { control: prop.control } : {}),
    })),
    tokens: source.metadata.tokens,
    a11y: source.metadata.a11y,
    guidance: source.metadata.guidance,
    source: source.source,
  }));
  return `// Generated by tools/build-manifest.ts. Do not edit.
export type ComponentControl =
  | { readonly kind: "boolean" }
  | { readonly kind: "text" }
  | { readonly kind: "select"; readonly values: readonly (string | number | boolean | null)[] };
export interface ComponentDocProp {
  readonly name: string;
  readonly description: string;
  readonly type: string;
  readonly required: boolean;
  readonly default?: string | number | boolean | null;
  readonly control?: ComponentControl;
}
export interface ComponentDoc {
  readonly name: string;
  readonly package: string;
  readonly category: string;
  readonly summary: string;
  readonly props: readonly ComponentDocProp[];
  readonly tokens: readonly string[];
  readonly a11y: { readonly role: string; readonly keyboard: readonly string[] };
  readonly guidance: { readonly do: readonly string[]; readonly dont: readonly string[] };
  readonly source: string;
}
export const componentDocs = Object.freeze(${JSON.stringify(docs, null, 2)} satisfies readonly ComponentDoc[]);
`;
}

export async function writeLoupeDocs(rawSources: readonly LoupeDocSource[]): Promise<void> {
  const sources = [...rawSources].sort((left, right) => left.metadata.name.localeCompare(right.metadata.name));
  const generatedRoot = fileURLToPath(new URL("../apps/loupe/src/generated/", import.meta.url));
  const examplesRoot = join(generatedRoot, "component-examples");
  await mkdir(examplesRoot, { recursive: true });
  const expected = new Set(["index.ts", ...sources.map(source => `${source.metadata.name}.tsx`)]);
  for (const entry of await readdir(examplesRoot, { withFileTypes: true })) {
    if (entry.isFile() && !expected.has(entry.name)) await unlink(join(examplesRoot, entry.name));
  }
  await Promise.all([
    writeFile(join(generatedRoot, "component-docs.ts"), generatedDocs(sources)),
    writeFile(join(examplesRoot, "index.ts"), generatedIndex(sources)),
    ...sources.map(source => writeFile(join(examplesRoot, `${source.metadata.name}.tsx`), generatedModule(source))),
  ]);
}
